// backend/services/patientService.js
const db = require('../models');
const { Op } = require('sequelize');
const patientCodeService = require('./patientCodeService');

class PatientService {
  /**
   * Get paginated list of patients with search
   */
  async getPatients({ page = 1, limit = 20, search = '', includeUser = true }) {
    const offset = (page - 1) * limit;

    const where = {};
    if (search) {
      where[Op.or] = [
        { first_name: { [Op.like]: `%${search}%` } },
        { last_name: { [Op.like]: `%${search}%` } },
        { contact_number: { [Op.like]: `%${search}%` } },
        { patient_facility_code: { [Op.like]: `%${search}%` } }
      ];
    }

    const include = [];
    if (includeUser) {
      include.push({
        model: db.User,
        as: 'User',
        attributes: ['id', 'username', 'email']
      });
    }

    const { count, rows } = await db.Patient.findAndCountAll({
      where,
      include,
      limit,
      offset,
      order: [['created_at', 'DESC']]
    });

    return {
      items: rows,
      total: count,
      page,
      totalPages: Math.ceil(count / limit)
    };
  }

  /**
   * Find patient by ID with optional includes
   */
  async getPatientById(id, includes = []) {
    const defaultIncludes = [
      {
        model: db.User,
        as: 'User',
        attributes: ['id', 'username', 'email']
      }
    ];

    const allIncludes = [...defaultIncludes, ...includes];

    const patient = await db.Patient.findByPk(id, {
      include: allIncludes
    });

    if (!patient) {
      throw new Error('Patient not found');
    }

    return patient;
  }

  /**
   * Find patient by contact number
   */
  async getPatientByContact(contactNumber) {
    return await db.Patient.findOne({
      where: { contact_number: contactNumber }
    });
  }

  /**
   * Find patient by user ID
   */
  async getPatientByUserId(userId) {
    return await db.Patient.findOne({
      where: { user_id: userId },
      include: [{
        model: db.User,
        as: 'User',
        attributes: ['username', 'email']
      }]
    });
  }

  /**
   * Search patients by name or contact
   */
  async searchPatients(query, limit = 10) {
    return await db.Patient.findAll({
      where: {
        [Op.or]: [
          { first_name: { [Op.like]: `%${query}%` } },
          { last_name: { [Op.like]: `%${query}%` } },
          { contact_number: { [Op.like]: `%${query}%` } },
          { patient_facility_code: { [Op.like]: `%${query}%` } }
        ]
      },
      include: [{
        model: db.User,
        as: 'User',
        attributes: ['id', 'username', 'email']
      }],
      limit,
      order: [['last_name', 'ASC']]
    });
  }

  /**
   * Create a new patient
   */
  async createPatient(patientData, userId = null) {
    // Check if contact number already exists
    const existing = await this.getPatientByContact(patientData.contact_number);
    if (existing) {
      throw new Error('Contact number already registered');
    }

    // Create patient (code will be auto-generated by hook)
    const patient = await db.Patient.create(patientData);

    return patient;
  }

  /**
   * Update a patient
   */
  async updatePatient(id, updates, userId = null, userRole = null) {
    const patient = await this.getPatientById(id);

    // If patient user, restrict updatable fields
    if (userRole === 'patient') {
      const userPatient = await this.getPatientByUserId(userId);
      if (!userPatient || userPatient.id !== patient.id) {
        throw new Error('Access denied');
      }

      // Patients can update these fields - ADDED guardian fields
      const allowedUpdates = [
        'address',
        'contact_number',
        'emergency_contact',
        'emergency_phone',
        'guardian_name',      // ADD THIS
        'guardian_contact'    // ADD THIS
      ];

      const filteredUpdates = {};
      Object.keys(updates).forEach(key => {
        if (allowedUpdates.includes(key)) {
          // Allow null values to be set
          filteredUpdates[key] = updates[key] === '' ? null : updates[key];
        }
      });
      updates = filteredUpdates;
    }

    // Get old data for audit
    const oldData = patient.toJSON();

    // Update
    await patient.update(updates);

    return {
      patient,
      oldData
    };
  }

  /**
   * Delete a patient (soft delete or hard delete)
   */
  async deletePatient(id, hardDelete = false) {
    const patient = await this.getPatientById(id);

    if (hardDelete) {
      await patient.destroy({ force: true });
      return { deleted: true, hard: true };
    } else {
      // Soft delete - update status
      await patient.update({ status: 'inactive' });
      return { deleted: true, hard: false, status: 'inactive' };
    }
  }

  /**
   * Get patient history (all encounters)
   */
  async getPatientHistory(id, userId = null, userRole = null) {
    // Check permissions
    if (userRole === 'patient') {
      const userPatient = await this.getPatientByUserId(userId);
      if (!userPatient || userPatient.id !== parseInt(id)) {
        throw new Error('Access denied');
      }
    }

    // Get testing encounters - Use 'User' as the alias, not 'Staff'
    const testingEncounters = await db.TestingEncounter.findAll({
      where: { patient_id: id },
      include: [{
        model: db.User,
        attributes: ['id', 'username']
      }],
      order: [['created_at', 'DESC']]
    });

    // Get treatment encounters - Use 'User' as the alias, not 'Staff'
    const treatmentEncounters = await db.TreatmentEncounter.findAll({
      where: { patient_id: id },
      include: [{
        model: db.User,
        attributes: ['id', 'username']
      }],
      order: [['created_at', 'DESC']]
    });

    return {
      testing: testingEncounters,
      treatment: treatmentEncounters
    };
  }

  /**
   * Regenerate facility code for a patient
   */
  async regeneratePatientCode(id) {
    const patient = await this.getPatientById(id);
    const oldCode = patient.patient_facility_code;
    const newCode = await patient.regenerateFacilityCode();
    await patient.save();

    return {
      patient,
      oldCode,
      newCode
    };
  }

  /**
   * Validate a facility code
   */
  validateCode(code) {
    return patientCodeService.validateFacilityCode(code);
  }

  /**
   * Parse a facility code
   */
  parseCode(code) {
    return patientCodeService.parseFacilityCode(code);
  }

  /**
   * Bulk generate codes
   */
  async bulkGenerateCodes(patients) {
    return await patientCodeService.bulkGenerateCodes(patients);
  }

  /**
   * Get patient statistics
   */
  async getPatientStats() {
    const total = await db.Patient.count();
    const byStatus = await db.Patient.findAll({
      attributes: [
        'status',
        [db.sequelize.fn('COUNT', db.sequelize.col('id')), 'count']
      ],
      group: ['status']
    });

    const byGender = await db.Patient.findAll({
      attributes: [
        'gender',
        [db.sequelize.fn('COUNT', db.sequelize.col('id')), 'count']
      ],
      group: ['gender']
    });

    const today = new Date().toISOString().split('T')[0];
    const registeredToday = await db.Patient.count({
      where: {
        created_at: {
          [Op.gte]: new Date(today)
        }
      }
    });

    return {
      total,
      registeredToday,
      byStatus: byStatus.map(item => ({
        status: item.status,
        count: parseInt(item.get('count'))
      })),
      byGender: byGender.map(item => ({
        gender: item.gender,
        count: parseInt(item.get('count'))
      }))
    };
  }
}

module.exports = new PatientService();